set_property IOSTANDARD LVCMOS33 [get_ports {score_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {score_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports buttom_player_left]
set_property IOSTANDARD LVCMOS33 [get_ports buttom_player_right]
set_property IOSTANDARD LVCMOS33 [get_ports rst]






set_property PACKAGE_PIN W20 [get_ports {score_left[3]}]
set_property PACKAGE_PIN W21 [get_ports {score_left[4]}]
set_property PACKAGE_PIN U20 [get_ports {score_left[2]}]
set_property PACKAGE_PIN V20 [get_ports {score_left[1]}]
set_property PACKAGE_PIN V18 [get_ports {score_left[0]}]
set_property PACKAGE_PIN V19 [get_ports {score_left[5]}]
set_property PACKAGE_PIN AA22 [get_ports {score_left[6]}]
set_property PACKAGE_PIN AA11 [get_ports {score_right[3]}]
set_property PACKAGE_PIN AB11 [get_ports {score_right[4]}]
set_property PACKAGE_PIN AA7 [get_ports {score_right[2]}] 
set_property PACKAGE_PIN AB2 [get_ports {score_right[1]}]
set_property PACKAGE_PIN AB1 [get_ports {score_right[0]}]
set_property PACKAGE_PIN AB5 [get_ports {score_right[5]}]
set_property PACKAGE_PIN AB7 [get_ports {score_right[6]}]
set_property PACKAGE_PIN U14 [get_ports {led_bus[7]}]
set_property PACKAGE_PIN U19 [get_ports {led_bus[6]}]
set_property PACKAGE_PIN W22 [get_ports {led_bus[5]}]
set_property PACKAGE_PIN V22 [get_ports {led_bus[4]}]
set_property PACKAGE_PIN U21 [get_ports {led_bus[3]}]
set_property PACKAGE_PIN U22 [get_ports {led_bus[2]}]
set_property PACKAGE_PIN T21 [get_ports {led_bus[1]}]
set_property PACKAGE_PIN T22 [get_ports {led_bus[0]}]
set_property PACKAGE_PIN R16 [get_ports buttom_player_right]
set_property PACKAGE_PIN Y9  [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports buttom_player_left]
set_property PACKAGE_PIN F22 [get_ports rst]